### ISSUE TITLE
Put together choregrapy movements according to given requirements

### ISSUE THREAD

**Issue by anastasiabolotnikova** [TeamPhilosopher/EestiMuusikaPaevadShow#2]

**Comment by anastasiabolotnikova** [comment]
90% of the movements ready. Creating a smaller issue for ramaining 10%

**Comment by 001shb** [comment]
Great

On Monday, February 23, 2015, anastasiabolotnikova <notifications@github.com>
wrote:

> 90% of the movements ready. Creating a smaller issue for ramaining 10%
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TeamPhilosopher/EestiMuusikaPaevadShow/issues/2#issuecomment-75548193>
> .
>


-- 

*Assoc. Prof. Dr. Gholamreza Anbarjafari (Sha**hab**)*
*iCV Group <http://icv.ims.ut.ee>,*
*IMS Lab <http://ims.ut.ee>, Institute of Technology,*
*University of Tartu, N**ooruse 1, *
*Tartu **50411 Estonia*
*http://www.ut.ee/~sjafari <http://www.ut.ee/~sjafari> *
